  version: 2.1
  orbs:
    # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
    node: circleci/node@5.0.2
    # different jobs are calles later in the workflows sections
  jobs:
    build:
      docker:
        # the base image can run most needed actions with orbs
        - image: "cimg/base:stable"
      steps:  
        - checkout
        - node/install:        
          node-version: '16.14'
 
        # install dependencies in both apps
        - run:
            name: install 
            command: |
              npm run install
        - run:
            name: test
            command: |
              npm run test
        - run:
            name: build
            command: |
              npm run build
  workflows:    
      build:
        jobs:    
          - build 
            filters:
              branches:
                only:
                  - master                  
              
